config/routes.rb
Rails.application.routes.draw do
#	get 'beerlist/index'

	get 'beers/tier-1-list' => 'beers#tier1list'
	get 'beers/tier-2-list' => 'beers#tier2list'
#	resources :beers

	get 'beers/beerlist' => 'beers#beerlist'
	resources :beers
	root 'beers#beerlist'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  http_basic_authenticate_with name: "enbw", password: "seanthony5150", except: [:beerlist, :index, :show, :tier1list, :tier2list]

	def beerlist
		@beers = Beer.all
	end

	def tier1list
		@beers = Beer.all
	end

	def tier2list
		@beers = Beer.all
	end

	def index
		@beers = Beer.all
	end

	def show
		@beer = Beer.find(params[:id])
	end

	def new
		@beer = Beer.new
	end

	def edit
		@beer = Beer.find(params[:id])
	end

	def create
		@beer = Beer.new(beer_params)

		if @beer.save
			redirect_to @beer
		else
			render 'new'
		end
	end

	def update
		@beer = Beer.find(params[:id])
			if @beer.update(beer_params)
		    	redirect_to @beer
 			else
			    render 'edit'
			end
	end

	def destroy
		@beer = Beer.find(params[:id])
		@beer.destroy

		redirect_to beers_path
	end

	private
		def beer_params
			params.require(:beer).permit(:name, :tagline, :abv, :tier, :ibu, :image, :ontap, :description, :index)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_with(model: @beer, local: true, :id =>"form", :class=>"topBefore") do |form| %>

  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@beer.errors.count, "error") %> prohibited
        this beer from being saved:
      </h2>
      <ul>
        <% @beer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :tagline %><br>
    <%= form.text_area :tagline %>
  </p>

  <p>
    <%= form.label :abv %><br>
    <%= form.text_field :abv %>
  </p>

  <p>
    <%= form.label :tier %><br>
    <%= form.text_field :tier %>
  </p>

  <p>
    <%= form.label :IBU %><br>
    <%= form.text_field :ibu %>
  </p>

  <p>
    <%= form.label :image %><br>
	<%= form.select :image, options_for_select(%w[enbwlogo.svg miromiel.svg cumberlandpunch.svg augustfest.svg coconutcremepie.svg eastbank.svg hipsterdanceparty.svg krautrock.svg roamingdog.svg swingbridge.svg thegrievance.svg wescoast.svg woodlandstreet.svg younghickory.svg fireofthecentury.svg brutwillis.svg eastmeetsweiss.svg dunkel.svg]) %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :ontap %>
	<%= form.check_box :ontap %>
  </p>

  <p>
    <%= form.label :index %>
	<%= form.number_field :index %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/beers/beerlist.html.erb
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>ENBW Beer List</title>
  <link rel="stylesheet" href="assets/css/main.css" />
<%= stylesheet_link_tag 'main', media: 'all' %>
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto:400,700" rel="stylesheet"/>
  <!-- <meta http-equiv="refresh" content="3000"> -->
</head>

  <body>
	<%= image_tag ("beer-list.svg"), :id => "beer-list" %>
<div id="white-container">
  <div id="beers">

  <% @beers.each do |beer| %>
  <% @beers.index.sort %>
	<% if beer.ontap == true %>
    	<div id="modalBtn<%= beer.image.chomp('.svg') %>" class="modalBtn<%= beer.image %> beer">
			<div class="logo-and-text">
				<% if beer.image == "enbwlogo.svg" %>
				<%= image_tag (beer.image), :class => "enbw-logo" %>
				<% else %>
				<%= image_tag (beer.image), :class => "beer-logo" %>
				<% end %>
				<div class="beer-text">
					<div class="beer-name"><%= beer.name %></div>
					<div class="beer-tagline"><%= beer.tagline %></div>
				</div>
			</div>
		        <div class="abv-and-tier">
		        	<div class="beer-abv">
		          		<div class="abv-text">ABV</div>
				        <div class="abv-content"><%= beer.abv %>%</div>
		        	</div>
		       		<div class="beer-tier">
		         		<div class="beer-tier-text">TIER</div>
		          		<div class="beer-tier-content"><%= beer.tier %></div>
		        	</div>
		      	</div>
		</div>
	<% end %>
  <% end %>


    <!-- Wine & Cider List -->
    <div id="wine-cider" class="beer">
        <div id="wine-cider-list">
          <div class="guest-total">
            <div class="guest-name">JACK'S HARD CIDER $5</div>
          </div>
          <div class="guest-total">
            <div class="guest-name">WINE $8</div>
          </div>
          <div class="guest-total">
            <div class="guest-name">SPARKLING ROS&Eacute; $9</div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="tier-pricing">
    <div class="tier">
      <div class="tier-main-name">TIER 1</div>
      <div class="taster">
        <div class="tier-name">5 OZ</div>
        <div class="tier-content">$2</div>
      </div>
      <div class="half-pint">
        <div class="tier-name">HALF PINT</div>
        <div class="tier-content">$3</div>
      </div>
      <div class="pint">
        <div class="tier-name">PINT</div>
        <div class="tier-content">$5</div>
      </div>
      <div class="crowler">
        <div class="tier-name">CROWLER</div>
        <div class="tier-content">$9</div>
      </div>
      <div class="growler">
        <div class="tier-name">GROWLER FILL</div>
        <div class="tier-content">$13</div>
      </div>
    </div>
    <div id="tier-2" class="tier">
      <div class="tier-main-name">TIER 2</div>
      <div class="taster">
        <div class="tier-name">5 OZ</div>
        <div class="tier-content">$3</div>
      </div>
      <div class="half-pint">
        <div class="tier-name">HALF PINT</div>
        <div class="tier-content">$4</div>
      </div>
      <div class="pint">
        <div class="tier-name">PINT</div>
        <div class="tier-content">$6</div>
      </div>
      <div class="crowler">
        <div class="tier-name">CROWLER</div>
        <div class="tier-content">$11</div>
      </div>
      <div class="growler">
        <div class="tier-name">GROWLER FILL</div>
        <div class="tier-content">$16</div>
      </div>
    </div>
</div>
</body>
</html>

app/views/beers/edit.html.erb
<%= stylesheet_link_tag 'form', media: 'all' %>
<title>Edit Beer</title>

<header>Edit Beer</header>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<%= stylesheet_link_tag 'form', media: 'all' %>
<title>Beer Index</title>

<h2><%= link_to 'Beer List', beers_beerlist_path %></h2>

<h2 class="beer-selection-header">Beers On Tap</h2>
  <ol>
  <% @beers.each do |beer| %>
	<% if beer.ontap == true %>
   	   <li class="beer-name"><%= beer.name %> &thinsp; <%=  link_to 'Edit', edit_beer_path(beer) =%><br></li>
	<% end %>
  <% end %>
  </ol>

<h2>Beers Not On Tap</h2>
  <ul>
  <% @beers.each do |beer| %>
	<% if beer.ontap == false %>
       <li class="beer-name"><%= beer.name %> &thinsp; <%=  link_to 'Edit', edit_beer_path(beer) =%></li>
	<% end %>
  <% end %>
  </ul>

<h2><%= link_to 'Add New Beer', new_beer_path %></h2>

app/views/beers/new.html.erb
<%= stylesheet_link_tag 'form', media: 'all' %>
<title>New Beer</title>

<header>New Beer</header>
<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Tagline:</strong>
  <%= @beer.tagline %>
</p>

<p>
  <strong>ABV:</strong>
  <%= @beer.abv %>
</p>
<p>
  <strong>Tier:</strong>
  <%= @beer.tier %>
</p>
<p>
  <strong>Description:</strong>
  <%= @beer.description %>
</p>
<p>
  <strong>IBU:</strong>
  <%= @beer.ibu %>
</p>
<p>
  <strong>Image Path:</strong>
  <%= @beer.image %>
</p>
<p>
  <strong>On Tap:</strong>
  <%= @beer.ontap %>
</p>
<p>
  <strong>Index Value:</strong>
  <%= @beer.index %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/beers/tier1list.html.erb
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>ENBW Beer List</title>
  <link rel="stylesheet" href="assets/css/tier-1.css" />
<%= stylesheet_link_tag 'tier-1', media: 'all' %>
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto:400,700" rel="stylesheet"/>
  <!-- <meta http-equiv="refresh" content="3000"> -->
</head>

  <body>
	<%= image_tag ("beer-list.svg"), :id => "beer-list" %>
<div id="white-container">
  <div id="beers">

  <% @beers.each do |beer| %>
  <% @beers.index.sort %>
	<% if beer.ontap == true && beer.tier == "1" %>
    	<div id="modalBtn<%= beer.image.chomp('.svg') %>" class="modalBtn<%= beer.image %> beer">
			<div class="logo-and-text">
				<% if beer.image == "enbwlogo.svg" %>
				<%= image_tag (beer.image), :class => "enbw-logo" %>
				<% else %>
				<%= image_tag (beer.image), :class => "beer-logo" %>
				<% end %>
				<div class="beer-text">
					<div class="beer-name"><%= beer.name %></div>
					<div class="beer-tagline"><%= beer.tagline %></div>
				</div>
			</div>
		        <div class="abv-and-tier">
		        	<div class="beer-abv">
		          		<div class="abv-text">ABV</div>
				        <div class="abv-content"><%= beer.abv %>%</div>
		        	</div>
		       		<div class="beer-tier">
		         		<div class="beer-tier-text">TIER</div>
		          		<div class="beer-tier-content"><%= beer.tier %></div>
		        	</div>
		      	</div>
		</div>
	<% end %>
  <% end %>


    <!-- Wine & Cider List -->
    <!--
<div id="wine-cider" class="beer">
        <div id="wine-cider-list">
          <div class="guest-total">
            <div class="guest-name">JACK'S HARD CIDER $5</div>
          </div>
          <div class="guest-total">
            <div class="guest-name">WINE $8</div>
          </div>
          <div class="guest-total">
            <div class="guest-name">SPARKLING ROS&Eacute; $9</div>
        </div>
      </div>
    </div>
-->
  </div>
</div>
<div class="tier-pricing">
    <div class="tier">
      <div class="tier-main-name">TIER 1</div>
      <div class="taster">
        <div class="tier-name">5 OZ</div>
        <div class="tier-content">$2</div>
      </div>
      <div class="half-pint">
        <div class="tier-name">HALF PINT</div>
        <div class="tier-content">$3</div>
      </div>
      <div class="pint">
        <div class="tier-name">PINT</div>
        <div class="tier-content">$5</div>
      </div>
      <div class="crowler">
        <div class="tier-name">CROWLER</div>
        <div class="tier-content">$9</div>
      </div>
      <div class="growler">
        <div class="tier-name">GROWLER FILL</div>
        <div class="tier-content">$13</div>
      </div>
    </div>
<!--
    <div id="tier-2" class="tier">
      <div class="tier-main-name">TIER 2</div>
      <div class="taster">
        <div class="tier-name">5 OZ</div>
        <div class="tier-content">$3</div>
      </div>
      <div class="half-pint">
        <div class="tier-name">HALF PINT</div>
        <div class="tier-content">$4</div>
      </div>
      <div class="pint">
        <div class="tier-name">PINT</div>
        <div class="tier-content">$6</div>
      </div>
      <div class="crowler">
        <div class="tier-name">CROWLER</div>
        <div class="tier-content">$11</div>
      </div>
      <div class="growler">
        <div class="tier-name">GROWLER FILL</div>
        <div class="tier-content">$16</div>
      </div>
    </div>
-->
</div>
</body>
</html>

app/views/beers/tier2list.html.erb
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>ENBW Beer List</title>
  <link rel="stylesheet" href="assets/css/tier-2.css" />
<%= stylesheet_link_tag 'tier-2', media: 'all' %>
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto:400,700" rel="stylesheet"/>
  <!-- <meta http-equiv="refresh" content="3000"> -->
</head>

  <body>
	<%= image_tag ("beer-list.svg"), :id => "beer-list" %>
<div id="white-container">
  <div id="beers">

  <% @beers.each do |beer| %>
  <% @beers.index.sort %>
	<% if beer.ontap == true && beer.tier == "2" %>
    	<div id="modalBtn<%= beer.image.chomp('.svg') %>" class="modalBtn<%= beer.image %> beer">
			<div class="logo-and-text">
				<% if beer.image == "enbwlogo.svg" %>
				<%= image_tag (beer.image), :class => "enbw-logo" %>
				<% else %>
				<%= image_tag (beer.image), :class => "beer-logo" %>
				<% end %>
				<div class="beer-text">
					<div class="beer-name"><%= beer.name %></div>
					<div class="beer-tagline"><%= beer.tagline %></div>
				</div>
			</div>
		        <div class="abv-and-tier">
		        	<div class="beer-abv">
		          		<div class="abv-text">ABV</div>
				        <div class="abv-content"><%= beer.abv %>%</div>
		        	</div>
		       		<div class="beer-tier">
		         		<div class="beer-tier-text">TIER</div>
		          		<div class="beer-tier-content"><%= beer.tier %></div>
		        	</div>
		      	</div>
		</div>
	<% end %>
  <% end %>

  <% @beers.each do |beer| %>
	<% if beer.ontap == true && beer.tier == "*" %>
    	<div id="modalBtn<%= beer.image.chomp('.svg') %>" class="modalBtn<%= beer.image %> beer">
			<div class="logo-and-text">
				<% if beer.image == "enbwlogo.svg" %>
				<%= image_tag (beer.image), :class => "enbw-logo" %>
				<% else %>
				<%= image_tag (beer.image), :class => "beer-logo" %>
				<% end %>
				<div class="beer-text">
					<div class="beer-name"><%= beer.name %></div>
					<div class="beer-tagline"><%= beer.tagline %></div>
				</div>
			</div>
		        <div class="abv-and-tier">
		        	<div class="beer-abv">
		          		<div class="abv-text">ABV</div>
				        <div class="abv-content"><%= beer.abv %>%</div>
		        	</div>
		       		<div class="beer-tier">
		         		<div class="beer-tier-text">TIER</div>
		          		<div class="beer-tier-content"><%= beer.tier %></div>
		        	</div>
		      	</div>
		</div>
	<% end %>
  <% end %>

    <div id="wine-cider" class="beer">
	<%= image_tag ("wine-cider.svg"), :id=> "wine-cider", :class=> "wine-cider-img" %>
      <div id="wine-cider-list">
          <div class="wine-cider-child">
            <div class="guest-name">Cabernet Sauvignon $8</div>
            <div class="guest-name">Malbec $8</div>
            <div class="guest-name">Sauvignon Blanc $8</div>
            <div class="guest-name">Sparkling Ros‌&eacute; $9</div>
          </div>
          <div class="wine-cider-child">
            <div class="guest-name">Original Sin Cider $6</div>
            <div class="guest-name">Dry Ros‌&eacute; Cider $6</div>
            <div class="guest-name">Blackberry Cider $6</div>
            <div class="guest-name">Nitro Cold Brew Coffee $3</div>
          </div>
      </div>
    </div>
  </div>
</div>
<div class="tier-pricing">
<!--
    <div class="tier">
      <div class="tier-main-name">TIER 1</div>
      <div class="taster">
        <div class="tier-name">5 OZ</div>
        <div class="tier-content">$2</div>
      </div>
      <div class="half-pint">
        <div class="tier-name">HALF PINT</div>
        <div class="tier-content">$3</div>
      </div>
      <div class="pint">
        <div class="tier-name">PINT</div>
        <div class="tier-content">$5</div>
      </div>
      <div class="crowler">
        <div class="tier-name">CROWLER</div>
        <div class="tier-content">$9</div>
      </div>
      <div class="growler">
        <div class="tier-name">GROWLER FILL</div>
        <div class="tier-content">$13</div>
      </div>
    </div>
-->
    <div id="tier-2" class="tier">
      <div class="tier-main-name">TIER 2</div>
      <div class="taster">
        <div class="tier-name">5 OZ</div>
        <div class="tier-content">$3</div>
      </div>
      <div class="half-pint">
        <div class="tier-name">HALF PINT</div>
        <div class="tier-content">$4</div>
      </div>
      <div class="pint">
        <div class="tier-name">PINT</div>
        <div class="tier-content">$6</div>
      </div>
      <div class="crowler">
        <div class="tier-name">CROWLER</div>
        <div class="tier-content">$11</div>
      </div>
      <div class="growler">
        <div class="tier-name">GROWLER FILL</div>
        <div class="tier-content">$16</div>
      </div>
    </div>
</div>
</body>
</html>